# profiles/github-actions/config.v8+.yaml
# Configured for exclusive use with GitHub Actions testing workflow
# See .github/workflows/main.yml

# Profile Settings
executor: slurm
use-singularity: true
use-conda: true
all-temp: true
show-failed-logs: true
verbose: true
jobs: 1
latency-wait: 120
default-resources:
  slurm_account: "runner"
  runtime: 3600
  mem_mb: 8000
  cpus_per_task: 1
