# profiles/slurm/config.v8+.yaml

executor: slurm
use-singularity: true
use-conda: true
conda-cleanup-pkgs: cache
verbose: true
show-failed-logs: true
jobs: 100 # Slurm jobscript size limit
default-resources:
  slurm_partition: "batch"
  slurm_account: "default"
  runtime: 4320
  mem_mb: 32000
  cpus_per_task: 12
  slurm_extra: '"--mail-type=ALL --mail-user=benjamin.bromberg@tufts.edu"'
